spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invest_assistant
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8099
springdoc:
  swagger-ui:
    path: /apiDocs.html
    enabled: true
    csrf:
      enabled: true

  api-docs:
    enabled: true

  packages-to-scan: neu.xindong.ia.controller

